/** Token and node types related to svelte in markdown. */
export const types = /** @type const */ ({
  svelteMarker: 'svelteMarker',
  svelteRawData: 'svelteRawData',
  svelteExpression: 'svelteExpression',
  svelteExpressionValue: 'svelteExpressionValue',
  svelteTag: 'svelteTag',
  svelteTagMarker: 'svelteTagMarker',
  svelteTagName: 'svelteTagName',
  svelteTagValue: 'svelteTagValue',
  svelteBlock: 'svelteBlock',
  svelteBlockTag: 'svelteBlockTag',
  svelteBlockTagMarker: 'svelteBlockTagMarker',
  svelteBlockTagName: 'svelteBlockTagName',
  svelteBlockTagValue: 'svelteBlockTagValue',
  svelteFlowElement: 'svelteFlowElement',
  svelteTextElement: 'svelteTextElement',
  svelteElementTag: 'svelteElementTag',
  svelteElementTagName: 'svelteElementTagName',
  svelteElementTagAttribute: 'svelteElementTagAttribute',
});
