/** Token and node types related to svelte in markdown. */
export const types = /** @type const */ ({
  svelteMarker: 'svelteMarker',
  svelteRawData: 'svelteRawData',
  svelteExpression: 'svelteExpression',
  svelteExpressionValue: 'svelteExpressionValue',
  svelteTag: 'svelteTag',
  svelteTagMarker: 'svelteTagMarker',
  svelteTagName: 'svelteTagName',
  svelteTagValue: 'svelteTagValue',
  svelteBlock: 'svelteBlock',
  svelteBlockTag: 'svelteBlockTag',
  svelteBlockTagMarker: 'svelteBlockTagMarker',
  svelteBlockTagName: 'svelteBlockTagName',
  svelteBlockTagValue: 'svelteBlockTagValue',
  svelteFlowElement: 'svelteFlowElement',
  // svelteFlowElementTag: 'svelteFlowElementTag',
  // svelteFlowElementTagName: 'svelteFlowElementTagName',
  // svelteFlowElementTagAttribute: 'svelteFlowElementTagAttribute',
  svelteTextElement: 'svelteTextElement',
  // svelteTextElementTag: 'svelteTextElementTag',
  // svelteTextElementTagName: 'svelteTextElementTagName',
  // svelteTextElementTagAttribute: 'svelteTextElementTagAttribute',
  svelteElementTag: 'svelteElementTag',
  svelteElementTagName: 'svelteElementTagName',
  svelteElementTagAttribute: 'svelteElementTagAttribute',
});
